=== Blake4809/vehicle-registration-xml-project/vehicle_registration_schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="VehicleRegistrationReport">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="OfficeCode" type="xs:string"/>
                <xs:element name="SubmissionDate" type="xs:date"/>
                <xs:element name="Vehicle" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="VIN" type="xs:string"/>
                            <xs:element name="PlateNumber" type="xs:string"/>
                            <xs:element name="OwnerName" type="xs:string"/>
                            <xs:element name="VehicleType" type="xs:string"/>
                            <xs:element name="ModelYear" type="xs:positiveInteger"/>
                            <xs:element name="Registered" type="xs:boolean"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== Blake4809/vehicle-registration-xml-project/vehicle_registration_report.xml
<VehicleRegistrationReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="vehicle_registration_schema.xsd">
    <OfficeCode>MI-073</OfficeCode>
    <SubmissionDate>2025-07-03</SubmissionDate>
    
    <Vehicle>
        <VIN>1HGCM82633A123456</VIN>
        <PlateNumber>ABC1234</PlateNumber>
        <OwnerName>Emily Clark</OwnerName>
        <VehicleType>Passenger</VehicleType>
        <ModelYear>2022</ModelYear>
        <Registered>true</Registered>
    </Vehicle>
    
    <Vehicle>
        <VIN>2FMDK3GC1BBB23456</VIN>
        <PlateNumber>XYZ7890</PlateNumber>
        <OwnerName>Michael Johnson</OwnerName>
        <VehicleType>Truck</VehicleType>
        <ModelYear>2020</ModelYear>
        <Registered>false</Registered>
    </Vehicle>
    
</VehicleRegistrationReport>
